### ISSUE TITLE
 git submodule update --init --recursive failed

### ISSUE THREAD

**Issue by todatamining** [peters/openalpr-windows#15]
I follow the instruction in "compile fails on tesseract #3"

> git clone https://github.com/openalpr/openalpr.git
> cd openalpr
> git clone https://github.com/peters/openalpr-windows.git windows
> cd windows
> git checkout v2.1.0
> git submodule update --init --recursive
> 

But get the following error:
```
Cloning into 'E:/github/openalpr/windows/opencv'...
Cloning into 'E:/github/openalpr/windows/tesseract-ocr/src'...
fatal: https://code.google.com/p/tesseract-ocr/info/refs not valid: is this a git repository?
fatal: clone of 'https://code.google.com/p/tesseract-ocr/' into submodule path 'E:/github/openalpr/ windows/tesseract-ocr/src' failed
```

It seems that it is due to https://code.google.com/p/tesseract-ocr/info/refs is redirect to github.
I clone the code manually:

cd windows
git checkout v2.1.0
git submodule update --init --recursive #this step failed 
git clone https://github.com/tesseract-ocr/tesseract.git tesseract-ocr/src   

Then got the following error:

> Get-Content : Cannot find path 'E:\github\openalpr\windows\tesseract-ocr\src\vs2010\libtesseract\libtesseract.vcxproj'
> because it does not exist.
> ....
>

**Comment by earthat** [comment]
Hi, did you get the solution of this issue. I am also facing the same.

**Comment by igitur** [comment]
Do `cd windows` before `git submodule update --init --recursive`
